# City Hub - Continuous Integration Setup for Azure Devops

trigger:
 batch: true
 branches:
   include:
   - master
   exclude:
   - v* #Exclude verions tags

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: build.yml
    parameters:
      name: Linux
      platform: linux

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: build.yml
    parameters:
      name: macOS
      platform: mac

- job: Windows_x64
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build.yml
    parameters:
      name: Windows_x64
      platform: win

# phases:
# - template: build.yml
#   parameters:
#     name: macOS
#     platform: mac
#     queue: Hosted macOS

# - template: build.yml
#   parameters:
#     name: Linux
#     platform: linux
#     queue: Hosted Ubuntu 1604

# - template: build.yml
#   parameters:
#     name: LinuxSnap
#     platform: linux
#     extra: snap
#     queue: Hosted Ubuntu 1604

# # - template: build.yml
# #   parameters:
# #     name: Windows_x86
# #     platform: win
# #     arch: x86
# #     queue: Hosted VS2017

# - template: build.yml
#   parameters:
#     name: Windows_x64
#     platform: win
#     queue: Hosted VS2017

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
