parameters:
  name: ''  # defaults for any parameters that aren't specified
  queue: ''
  arch: ''
  configuration: ''

phases:
- phase: ${{ parameters.name }}
  queue: ${{ parameters.queue }}

    # parallel: 2
    # matrix:
    # x64_release:
    #   arch: x64
    #   configuration: release
    # x86_release:
    #   arch: x86
    #   configuration: release

  steps:
  - script: echo hello from $(parameters.name) and $(parameters.queue) and $(parameters.arch) and $(parameters.configuration)
  #- script: npm install
  #- script: npm test