parameters:
  name: ''
  queue: ''
  displayName: ''
  arch: ''
  configuration: ''

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
    matrix:
        x64_debug:
          buildArch: x64
          buildConfig: debug
        x64_release:
          buildArch: x64
          buildConfig: release
        x86_release:
          buildArch: x86
          buildConfig: release
  steps:
  - script: build arch=$(buildArch) config=$(buildConfig)
  # - script: echo hello from $(parameters.name) and $(parameters.queue) and $(arch) and $(parameters.configuration)
  # - script: "echo $(arch) $(configuration) --- $(parameters.arch) $(parameters.configuration)"
  # - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the $(configuration) value"
  #- script: npm install
  #- script: npm test