parameters:
  name: ''
  queue: ''
  displayName: ''
  arch: ''
  configuration: ''

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
    parallel: 2
    matrix:
      debug:
        configuration: debug
        platform: x64
      release:
        configuration: release
        platform: x64
  steps:
  - script: echo hello from $(parameters.name) and $(parameters.queue) and $(arch) and $(parameters.configuration)
  - script: "echo $(arch) $(configuration) --- $(parameters.arch) $(parameters.configuration)"
  - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the $(configuration) value"
  #- script: npm install
  #- script: npm test