parameters:
  name: ''
  queue: ''
  platform: ''
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do Debug if specified

phases:
- phase: ${{ parameters.name }}
  #displayName: ${{ parameters.displayName }}
  displayName: ${{ format('City Hub ({0}-{1})', parameters.platform, parameters.arch) }}
  queue: ${{ parameters.queue }}
  steps:

  - task: NodeTool@0
    displayName: upgrade node
    inputs:
      versionSpec: '8.x' # Required by Angular 6

  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false

  - task: Npm@1
    displayName: npm run publish
    inputs:
      command: custom
      verbose: false
      ${{ if eq(parameters.platform, 'win') }}:
        customCommand: ${{ format('run publish:{0}:{1}', parameters.platform, parameters.arch) }} 
      ${{ if ne(parameters.platform, 'win') }}:
        customCommand: ${{ format('run publish:{0}', parameters.platform) }} 
    env:
      GH_TOKEN: $(GH_TOKEN)

    # Not able to use matrix setup in the template, figure out how to do that in the future to more easily build different outputs on the same agent instance.
    # matrix:
    #     x64_debug:
    #       buildArch: x64
    #       buildConfig: debug
    #     x64_release:
    #       buildArch: x64
    #       buildConfig: release
    #     x86_release:
    #       buildArch: x86
    #       buildConfig: release
  # steps:
  # - script: echo hello from $(parameters.name) and $(parameters.queue) and $(arch) and $(parameters.configuration)
  # - task: DotNetCoreCLI@2
  #   displayName: dotnet publish
  #   inputs:
  #     command: publish
  #     arguments: '-c ${{ parameters.configuration }} -r ${{ parameters.platform }}-${{ parameters.arch }} -v m'
  #     workingDirectory: 'src/city-chain/src/City.Chain'

# steps:
# - task: DotNetCoreCLI@2
#   displayName: dotnet publish
#   inputs:
#     command: publish
#     arguments: '-c release'
#     workingDirectory: 'src/app'


  #- script: build arch=$(arch) config=$(buildConfig)
   
  # - script: "echo $(arch) $(configuration) --- $(parameters.arch) $(parameters.configuration)"
  # - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the $(configuration) value"
  #- script: npm install
  #- script: npm test