parameters:
  name: ''
  queue: ''
  platform: ''
  daemon: '0.0.2' # Version of the daemon to download
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do Debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ format('City Hub ({0}-{1})', parameters.platform, parameters.arch) }}
  queue: ${{ parameters.queue }}
  steps:

  - task: NodeTool@0
    displayName: upgrade node
    inputs:
      versionSpec: '8.x' # Required by Angular 6

  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false

  - powershell: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      $url = "https://github.com/CityChainFoundation/city-chain/releases/download/v{0}/City.Chain-{0}-{1}-{2}.{3}" -f $env:daemon, $env:platform, $env:arch, $env:extension
      $output = Join-Path -Path "$Env:BUILD_SOURCESDIRECTORY" -ChildPath "daemon.zip"
      Write-Output "Url: $url"
      Write-Output "Path: $output"
      $start_time = Get-Date
      (New-Object System.Net.WebClient).DownloadFile($url, $output)
      Write-Host "AGENT_WORKFOLDER contents:"
      gci $Env:AGENT_WORKFOLDER
      Write-Host "AGENT_BUILDDIRECTORY contents:"
      gci $Env:AGENT_BUILDDIRECTORY
      Write-Host "BUILD_SOURCESDIRECTORY contents:"
      gci $Env:BUILD_SOURCESDIRECTORY
      Write-Output "Saved: $output"
      Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)" 
    displayName: Download daemon
    workingDirectory: $(build.SourcesDirectory)
    env:
      daemon: ${{ parameters.daemon }}
      platform: ${{ parameters.platform }}
      arch: ${{ parameters.arch }}

      ${{ if eq(parameters.platform, 'linux') }}:
        extension: "tar.gz"
      ${{ if ne(parameters.platform, 'linux') }}:
        extension: "zip"

  - task: ExtractFiles@1
    displayName: Extract files 
    inputs:
      archiveFilePatterns: 'daemon.zip'
      destinationFolder: daemon

  - task: Npm@1
    displayName: npm run publish
    inputs:
      command: custom
      verbose: false
      ${{ if eq(parameters.platform, 'win') }}:
        customCommand: ${{ format('run publish:{0}:{1}', parameters.platform, parameters.arch) }} 
      ${{ if ne(parameters.platform, 'win') }}:
        customCommand: ${{ format('run publish:{0}', parameters.platform) }} 
    env:
      GH_TOKEN: $(GH_TOKEN)
